### ISSUE TITLE
Progress Tracker: Heap & Node class methods

### ISSUE THREAD

**Issue by klaudiosinani** [klaussinani/mheap#3]
## Description

The following issue will act as a progress tracking thread, regarding the implementation of the exposed `Heap` & `Node` class methods:

### Heap Methods

- [x] `Heap#size`
- [x] `Heap#root`
- [x] `Heap#toPairs()`
- [x] `Heap#includes(key)`
- [x] `Heap#isEmpty()`
- [x] `Heap#toArray()`
- [x] `Heap#clear()`
- [x] `Heap#extract(index)`
- [x] `Heap#extractMin()`
- [x] `Heap#extractMax()`
- [x] `Heap#remove(index)`
- [x] `Heap#values()`
- [x] `Heap#keys()`
- [x] `Heap#search(key)`
- [x] `Heap#right(index)`
- [x] `Heap#rightIndex(index)`
- [x] `Heap#left(index)`
- [x] `Heap#leftIndex(index)`
- [x] `Heap#partialNodes()`
- [x] `Heap#parentIndex(index)`
- [x] `Heap#parent(index)`
- [x] `Heap#node(index)`
- [x] `Heap#minChild(index)`
- [x] `Heap#minChildIndex(index)`
- [x] `Heap#maxChild(index)`
- [x] `Heap#maxChildIndex(index)`
- [x] `Heap#leafNodes()`
- [x] `Heap#isPartialNode(index)`
- [x] `Heap#isFullNode(index)`
- [x] `Heap#isLeafNode(index)`
- [x] `Heap#InternalNode(index)`
- [x] `Heap#height()`
- [x] `Heap#indexOf(key)`
- [x] `Heap#degree(index)`
- [x] `Heap#children(index)`
- [x] `Heap#childrenIndices(index)`

### Node Methods

- [x] `Node#value`
- [x] `Node#key`
- [x] `Node#toPair()`
